### ISSUE TITLE
Error: Sensor for this model was not camera, but 1

### ISSUE THREAD

**Issue by kaisark** [edgeimpulse/example-linux-with-twilio#1]
I used the example model and ran into an error on the Jetson Nano (Ubuntu 18/Python3). I saw that "Parameters image size 0x0 px (0 channels) classes [ 'faucet', 'noise' ]" was somehow being referenced, however those classes are from another project. Is there a configuration issue?

edge-impulse-linux-runner --download twilio-example.eim

------------------------------
(py36dl) username@nano:~/projects/edgeimpulse/example-linux-with-twilio$ node build/webserver-twilio.js twilio-example.eim "UVC Camera (046d"
Starting the image classifier for username / username-project-1 (v4)
Parameters image size 0x0 px (0 channels) classes [ 'faucet', 'noise' ]
Using camera UVC Camera (046d starting...
Connected to camera
Error: Sensor for this model was not camera, but 1
    at ImageClassifier.start (/home/username/projects/edgeimpulse/example-linux-with-twilio/node_modules/edge-impulse-linux/build/library/classifier/image-classifier.js:28:19)
    at /home/username/projects/edgeimpulse/example-linux-with-twilio/build/webserver-twilio.js:73:31

**Comment by kaisark** [comment]
Solved. I just needed to run  "edge-impulse-linux --clean" to switch projects.

(py36dl) username@nano:~/projects/edgeimpulse$ edge-impulse-linux --clean
Edge Impulse Linux client v1.2.3

What is your user name or e-mail address (edgeimpulse.com)? [hidden]
? What is your password? [hidden]

? To which project do you want to connect this device? [hidden] / object-detection
? Select a microphone (or run this command with --disable-microphone to skip selection) USB-Audio - T
ONOR TC-777 Audio Device
[SER] Using microphone hw:3,0
? Select a camera (or run this command with --disable-camera to skip selection) UVC Camera (046d
[SER] Using camera UVC Camera (046d starting...
[SER] Connected to camera
[WS ] Connecting to wss://remote-mgmt.edgeimpulse.com
[WS ] Connected to wss://remote-mgmt.edgeimpulse.com
? What name do you want to give this device? Jetson Nano
[WS ] Device "Jetson Nano" is now connected to project "object-detection"
